---
# repo: jomrr/ansible-role-httpd
# file: handlers/main.yml

- name: "Reload httpd"
  ansible.builtin.service:
    name: "{{ httpd_service_name }}"
    state: reloaded

- name: "Restart httpd"
  ansible.builtin.service:
    name: "{{ httpd_service_name }}"
    state: restarted
